# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a40f538e68e92ae1c27d76c181b6ff8d964714b84d198174effd9804704e034943417fcedc13e0d92ff23a0e47c17020cd98e2da35bc0af34927ee048fed103f

test:
  secret_key_base: 1c715f204074f04e6d5dd2307abcb82b844a466ddf498bfaf336880ff730f58cba9ec8a1ada9fe77943a423a4bc9b49e8a4432226d709be2ccc2f840e8e7c94a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
